# Generated by Django 5.2.1 on 2025-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_url_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='target_url',
            field=models.URLField(default='https://example.com123'),
            preserve_default=False,
        ),
    ]
